# Generated by Django 2.1.2 on 2018-10-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181028_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='horarios',
        ),
    ]
